workflows:
  firebase-distribution:
    name: Firebase App Distribution
    max_build_duration: 30
    environment:
      flutter: stable
      groups:
        - firebase_credentials
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: "main"
          include: true
    scripts:
      - name: Install dependencies
        script: flutter pub get

      - name: Build APK
        script: flutter build apk --release

      - name: Upload to Firebase App Distribution
        script: |
          firebase appdistribution:distribute build/app/outputs/flutter-apk/app-release.apk \
            --app $FIREBASE_APP_ID \
            --token $FIREBASE_AUTH_TOKEN \
            --groups testers
